#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

event_link("dovecot-acl", "email-update", "85");
event_link("dovecot-acl", "user-create", "85");

safe_touch("root/etc/dovecot/sharedmailbox/dict.db");
